segmentation:
  method: "grabcut+otsu"

calibration:
  enabled: True
  roi_fraction: 0.15
  square_size: 1.0 # in mm
  position: null # position of the scalebar in the image
  template_path: scalebar_template.jpg

points_of_interest:
  enabled: True
