segmentation:
  method: "grabcut+otsu"

calibration:
  enabled: True
  scalebar_size: MEDIUM # rough estimate of the scalebar size - SMALL: 10%, MEDIUM: 30%, or LARGE: 50% of the smallest dimension of the image
  square_size: 1.0 # in mm
  position: bottom_left # position of the scalebar in the image

points_of_interest:
  enabled: True
