reading:
  rgb_regex: (.+)\.tif
  uv_regex: (.+)uv\.tif
  uv_channel_index: 0

  extensions: [.tif]
  ordered: false

segmentation:
  method: "grabcut+otsu"
  channel: saturation
  rescale: 0.5

calibration:
  enabled: True
  max_corners: 50
  roi_fraction: 0.15
  square_size: 1.0 # in mm
  position: null # position of the scalebar in the image
  template_path: scalebar_template.jpg
  template_scale: 290.0 # in pixels per mm

points_of_interest:
  enabled: True
